### PR TITLE
Implement Favorites count feature

### PR DESCRIPTION
**Pull request by Kasulejoseph**
What does this PR do?
- Displays the number of times an Idea as been favorited.

Any relevant screenshot(s)?
-
Screenshot 2019-10-26 at 09 59 50

### CODE REVIEW

**Comment by MuhaddiMu** [comment]
@all-contributors please add @Kasulejoseph for code

**Comment by MuhaddiMu** [comment]
Hi, @Kasulejoseph Thank you very much for your contribution :medal_sports: 

I am encountering a few bugs if you can further contribute to fixing them.

1)  As you mentioned in the email, Unexpectedly all Ideas remove from favourite when you mark 3-4 Ideas favourite and then if you remove one, all of them get removed. @markrmessmore your thoughts on this?

2) When you filter ideas to display only the favourite one sometimes you'll notice that it is displaying all of the ideas, not the favourite ones. 

3) When filtering ideas(due to not reactivity of Vue on the objects, we are refreshing the list of ideas) which results in the improper user experience of the idea cards. If you can look into it

**Comment by MuhaddiMu** [comment]
P.S: I have changed deployment to Netlify. On every push to master, it'll be automatically deployed and we can also be able to see how the Pull request looks like on the production.

**Comment by Kasulejoseph** [comment]
Sure. Let me fix some of the bugs you've mentioned here.

**Pull request merged**
